### ISSUE TITLE
Errors when adding a single import

### ISSUE THREAD

**Issue by petobens** [tweekmonster/impsort.vim#25]
Hi @tweekmonster. I don't know if something changed with jedi or what but whenever I add an import (even with an empty file) such as:
```
import numpy as np
```
i keep getting `[impsort]` (error) message. Do you plan to update this repo? I rely on `impsort.vim` on a daily basis :) Thank you!!!

**Comment by petobens** [comment]
It's probably this function (since i'm using neovim) https://github.com/tweekmonster/impsort.vim/blob/e569e9911f6ed5b91096703819b6923b2486e479/autoload/impsort.vim#L987  But i have no idea how to debug further.

**Comment by petobens** [comment]
This is the traceback:
```
[impsort] Traceback (most recent call last):
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/imports.py", line 47, in <module>
[impsort]
[impsort]     get_names(sys.argv[1], source)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/imports.py", line 35, in get_names
[impsort]     print('%s,%s' % (c.name, c.type))
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/api/classes.py", line 146, in type
[impsort]     for context in self._name.infer():
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/filters.py", line 82, in infer
[impsort]     return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/finder.py", line 188, in _name_to_types
[impsort]     types = imports.infer_import(context, tree_name)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/cache.py", line 41, in wrapper
[impsort]     rv = function(obj, *args, **kwargs)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/imports.py", line 69, in infer_import
[impsort]     ) for t in types
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/common.py", line 186, in unite
[impsort]     return set(typ for types in iterable for typ in types)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/common.py", line 186, in <genexpr>
[impsort]     return set(typ for types in iterable for typ in types)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/imports.py", line 69, in <genexpr>
[impsort]     ) for t in types
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/_compatibility.py", line 185, in <lambda>
[impsort]     return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/context.py", line 54, in py__getattribute__
[impsort]     self, name_or_str, name_context, position, search_global, is_goto)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 129, in find_types
[impsort]     return f.find(filters, attribute_lookup=not search_global)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/debug.py", line 81, in wrapper
[impsort]     return func(*args, **kwargs)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/finder.py", line 63, in find
[impsort]     types = self._names_to_types(names, attribute_lookup)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/finder.py", line 140, in _names_to_types
[impsort]     types = unite(name.infer() for name in names)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/common.py", line 186, in unite
[impsort]     return set(typ for types in iterable for typ in types)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/common.py", line 186, in <genexpr>
[impsort]
[impsort]     return set(typ for types in iterable for typ in types)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/finder.py", line 140, in <genexpr>
[impsort]     types = unite(name.infer() for name in names)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/filters.py", line 82, in infer
[impsort]     return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/finder.py", line 184, in _name_to_types
[impsort]     types = _remove_statements(evaluator, context, node, tree_name)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/finder.py", line 269, in _remove_statements
[impsort]     types |= context.eval_stmt(stmt, seek_name=name)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/context.py", line 42, in eval_stmt
[impsort]     return self.evaluator.eval_statement(self, stmt, seek_name)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 134, in eval_statement
[impsort]     return self._eval_stmt(context, stmt, seek_name)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/debug.py", line 81, in wrapper
[impsort]     return func(*args, **kwargs)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 150, in _eval_stmt
[impsort]     types = self.eval_element(context, rhs)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 250, in eval_element
[impsort]     return self._eval_element_if_evaluated(context, element)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 262, in _eval_element_if_evaluated
[impsort]
[impsort]     return self._eval_element_cached(context, element)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/cache.py", line 41, in wrapper
[impsort]     rv = function(obj, *args, **kwargs)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 266, in _eval_element_cached
[impsort]     return self._eval_element_not_cached(context, element)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/debug.py", line 81, in wrapper
[impsort]     return func(*args, **kwargs)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 273, in _eval_element_not_cached
[impsort]     types = self.eval_atom(context, element)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 363, in eval_atom
[impsort]
[impsort]     return self.eval_element(context, c[1])
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 250, in eval_element
[impsort]     return self._eval_element_if_evaluated(context, element)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 262, in _eval_element_if_evaluated
[impsort]     return self._eval_element_cached(context, element)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/cache.py", line 41, in wrapper
[impsort]     rv = function(obj, *args, **kwargs)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 266, in _eval_element_cached
[impsort]     return self._eval_element_not_cached(context, element)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/debug.py", line 81, in wrapper
[impsort]     return func(*args, **kwargs)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 292, in _eval_element_not_cached
[impsort]     types = self.eval_trailer(context, types, trailer)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 410, in eval_trailer
[impsort]
[impsort]     new_types |= self.execute(typ, arguments)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/debug.py", line 81, in wrapper
[impsort]     return func(*args, **kwargs)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/__init__.py", line 426, in execute
[impsort]     return stdlib.execute(self, obj, arguments)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/stdlib.py", line 55, in execute
[impsort]     return func(evaluator, obj, arguments)
[impsort]   File "/Users/pedro/git-repos/private/dotfiles/vim/bundle/repos/github.com/tweekmonster/impsort.vim/bin/jedi/jedi/evaluate/stdlib.py", line 244, in collections_namedtuple
[impsort]     _fields = list(_follow_param(evaluator, arguments, 1))[0]
[impsort]
[impsort] IndexError: list index out of range
[impsort]
[impsort]
```

**Comment by tweekmonster** [comment]
I'll take a look.
